const locality_data = [
  {
    display_name: '[PAIS] Argentina',
    name: '[PAIS] Argentina',
    sector: '',
    region: 'Sin especificar',
    country: 'Argentina',
  },
  {
    display_name: 'Neuquén',
    name: 'Neuquén',
    sector: '',
    region: 'Sin especificar',
    country: 'Argentina',
  },
  {
    display_name: 'San Martín',
    name: 'San Martín',
    sector: '',
    region: 'Sin especificar',
    country: 'Argentina',
  },
  {
    display_name: '[PAIS] Bolivia',
    name: '[PAIS] Bolivia',
    sector: '',
    region: 'Sin especificar',
    country: 'Bolivia',
  },
  {
    display_name: '[PAIS] Brasil',
    name: '[PAIS] Brasil',
    sector: '',
    region: 'Sin especificar',
    country: 'Brasil',
  },
  {
    display_name: 'Concepción',
    name: 'Concepción',
    sector: '',
    region: 'Biobío',
    country: 'Chile',
  },
  {
    display_name: 'Coronel',
    name: 'Coronel',
    sector: '',
    region: 'Biobío',
    country: 'Chile',
  },
  {
    display_name: 'Los Ángeles',
    name: 'Los Ángeles',
    sector: '',
    region: 'Biobío',
    country: 'Chile',
  },
  {
    display_name: 'Talcahuano',
    name: 'Talcahuano',
    sector: '',
    region: 'Biobío',
    country: 'Chile',
  },
  {
    display_name: 'La Serena',
    name: 'La Serena',
    sector: '',
    region: 'Coquimbo',
    country: 'Chile',
  },
  {
    display_name: 'Angol',
    name: 'Angol',
    sector: '',
    region: 'La Araucanía',
    country: 'Chile',
  },
  {
    display_name: 'Central Alhueco',
    name: 'Central Alhueco',
    sector: '',
    region: 'La Araucanía',
    country: 'Chile',
  },
  {
    display_name: 'Cholchol',
    name: 'Cholchol',
    sector: '',
    region: 'La Araucanía',
    country: 'Chile',
  },
  {
    display_name: 'Cunco',
    name: 'Cunco',
    sector: '',
    region: 'La Araucanía',
    country: 'Chile',
  },
  {
    display_name: 'Curaco',
    name: 'Curaco',
    sector: '',
    region: 'La Araucanía',
    country: 'Chile',
  },
  {
    display_name: 'Gorbea',
    name: 'Gorbea',
    sector: '',
    region: 'La Araucanía',
    country: 'Chile',
  },
  {
    display_name: 'Hualpín',
    name: 'Hualpín',
    sector: '',
    region: 'La Araucanía',
    country: 'Chile',
  },
  {
    display_name: 'Lautaro',
    name: 'Lautaro',
    sector: '',
    region: 'La Araucanía',
    country: 'Chile',
  },
  {
    display_name: 'Lonquimay',
    name: 'Lonquimay',
    sector: '',
    region: 'La Araucanía',
    country: 'Chile',
  },
  {
    display_name: 'Paillao Mapu',
    name: 'Paillao Mapu',
    sector: '',
    region: 'La Araucanía',
    country: 'Chile',
  },
  {
    display_name: 'Pitrufquén',
    name: 'Pitrufquén',
    sector: '',
    region: 'La Araucanía',
    country: 'Chile',
  },
  {
    display_name: 'Pucón',
    name: 'Pucón',
    sector: '',
    region: 'La Araucanía',
    country: 'Chile',
  },
  {
    display_name: 'Pullallán',
    name: 'Pullallán',
    sector: '',
    region: 'La Araucanía',
    country: 'Chile',
  },
  {
    display_name: 'Rucacura',
    name: 'Rucacura',
    sector: '',
    region: 'La Araucanía',
    country: 'Chile',
  },
  {
    display_name: 'Temuco',
    name: 'Temuco',
    sector: '',
    region: 'La Araucanía',
    country: 'Chile',
  },
  {
    display_name: 'Temuco - Altamira',
    name: 'Temuco',
    sector: 'Altamira',
    region: 'La Araucanía',
    country: 'Chile',
  },
  {
    display_name: 'Temuco - Amanecer',
    name: 'Temuco',
    sector: 'Amanecer',
    region: 'La Araucanía',
    country: 'Chile',
  },
  {
    display_name: 'Temuco - Fundo El Carmen',
    name: 'Temuco',
    sector: 'Fundo El Carmen',
    region: 'La Araucanía',
    country: 'Chile',
  },
  {
    display_name: 'Temuco - La Paz MacIver',
    name: 'Temuco',
    sector: 'La Paz MacIver',
    region: 'La Araucanía',
    country: 'Chile',
  },
  {
    display_name: 'Temuco - Labranza',
    name: 'Temuco',
    sector: 'Labranza',
    region: 'La Araucanía',
    country: 'Chile',
  },
  {
    display_name: 'Temuco - Las Lomas',
    name: 'Temuco',
    sector: 'Las Lomas',
    region: 'La Araucanía',
    country: 'Chile',
  },
  {
    display_name: 'Temuco - Los Caciques',
    name: 'Temuco',
    sector: 'Los Caciques',
    region: 'La Araucanía',
    country: 'Chile',
  },
  {
    display_name: 'Temuco - Padre Las Casas',
    name: 'Temuco',
    sector: 'Padre Las Casas',
    region: 'La Araucanía',
    country: 'Chile',
  },
  {
    display_name: 'Temuco - Pedro de Valdivia',
    name: 'Temuco',
    sector: 'Pedro de Valdivia',
    region: 'La Araucanía',
    country: 'Chile',
  },
  {
    display_name: 'Temuco - Pueblo Nuevo',
    name: 'Temuco',
    sector: 'Pueblo Nuevo',
    region: 'La Araucanía',
    country: 'Chile',
  },
  {
    display_name: 'Temuco - Trañi Trañi',
    name: 'Temuco',
    sector: 'Trañi Trañi',
    region: 'La Araucanía',
    country: 'Chile',
  },
  {
    display_name: 'Temuco - Turingia',
    name: 'Temuco',
    sector: 'Turingia',
    region: 'La Araucanía',
    country: 'Chile',
  },
  {
    display_name: 'Temuco - Villa Los Ríos',
    name: 'Temuco',
    sector: 'Villa Los Ríos',
    region: 'La Araucanía',
    country: 'Chile',
  },
  {
    display_name: 'Toltén',
    name: 'Toltén',
    sector: '',
    region: 'La Araucanía',
    country: 'Chile',
  },
  {
    display_name: 'Villarrica',
    name: 'Villarrica',
    sector: '',
    region: 'La Araucanía',
    country: 'Chile',
  },
  {
    display_name: 'Osorno',
    name: 'Osorno',
    sector: '',
    region: 'Los Lagos',
    country: 'Chile',
  },
  {
    display_name: 'Puerto Montt',
    name: 'Puerto Montt',
    sector: '',
    region: 'Los Lagos',
    country: 'Chile',
  },
  {
    display_name: 'Lanco',
    name: 'Lanco',
    sector: '',
    region: 'Los Ríos',
    country: 'Chile',
  },
  {
    display_name: 'Los Lagos',
    name: 'Los Lagos',
    sector: '',
    region: 'Los Ríos',
    country: 'Chile',
  },
  {
    display_name: 'Panguipulli',
    name: 'Panguipulli',
    sector: '',
    region: 'Los Ríos',
    country: 'Chile',
  },
  {
    display_name: 'Punta Arenas',
    name: 'Punta Arenas',
    sector: '',
    region: 'Magallanes',
    country: 'Chile',
  },
  {
    display_name: 'Talca',
    name: 'Talca',
    sector: '',
    region: 'Maule',
    country: 'Chile',
  },
  {
    display_name: 'Santiago - Centro',
    name: 'Santiago',
    sector: 'Centro',
    region: 'Metropolitana',
    country: 'Chile',
  },
  {
    display_name: 'Santiago - Cerrillos',
    name: 'Santiago',
    sector: 'Cerrillos',
    region: 'Metropolitana',
    country: 'Chile',
  },
  {
    display_name: 'Santiago - Colina',
    name: 'Santiago',
    sector: 'Colina',
    region: 'Metropolitana',
    country: 'Chile',
  },
  {
    display_name: 'Santiago - La Cisterna',
    name: 'Santiago',
    sector: 'La Cisterna',
    region: 'Metropolitana',
    country: 'Chile',
  },
  {
    display_name: 'Santiago - La Florida',
    name: 'Santiago',
    sector: 'La Florida',
    region: 'Metropolitana',
    country: 'Chile',
  },
  {
    display_name: 'Santiago - Las Condes',
    name: 'Santiago',
    sector: 'Las Condes',
    region: 'Metropolitana',
    country: 'Chile',
  },
  {
    display_name: 'Santiago - Maipú',
    name: 'Santiago',
    sector: 'Maipú',
    region: 'Metropolitana',
    country: 'Chile',
  },
  {
    display_name: 'Santiago - Peñaflor',
    name: 'Santiago',
    sector: 'Peñaflor',
    region: 'Metropolitana',
    country: 'Chile',
  },
  {
    display_name: 'Santiago - Peñalolén',
    name: 'Santiago',
    sector: 'Peñalolén',
    region: 'Metropolitana',
    country: 'Chile',
  },
  {
    display_name: 'Santiago - Pudahuel',
    name: 'Santiago',
    sector: 'Pudahuel',
    region: 'Metropolitana',
    country: 'Chile',
  },
  {
    display_name: 'Santiago - Puente Alto',
    name: 'Santiago',
    sector: 'Puente Alto',
    region: 'Metropolitana',
    country: 'Chile',
  },
  {
    display_name: 'Santiago - Recoleta',
    name: 'Santiago',
    sector: 'Recoleta',
    region: 'Metropolitana',
    country: 'Chile',
  },
  {
    display_name: 'Santiago - San Bernardo',
    name: 'Santiago',
    sector: 'San Bernardo',
    region: 'Metropolitana',
    country: 'Chile',
  },
  {
    display_name: 'Rancagua',
    name: 'Rancagua',
    sector: '',
    region: "O'Higgins",
    country: 'Chile',
  },
  {
    display_name: 'Iquique',
    name: 'Iquique',
    sector: '',
    region: 'Tarapacá',
    country: 'Chile',
  },
  {
    display_name: '[PAIS] Colombia',
    name: '[PAIS] Colombia',
    sector: '',
    region: 'Sin especificar',
    country: 'Colombia',
  },
  {
    display_name: '[PAIS] Cuba',
    name: '[PAIS] Cuba',
    sector: '',
    region: 'Sin especificar',
    country: 'Cuba',
  },
];

export default locality_data;
