const locality_data = [
  {
    sector: '',
    region: 'Sin especificar',
    display_name: '[PAIS] Argentina',
    country: 'Argentina',
    name: '[PAIS] Argentina',
    id: 'EE5Gnfmvq9Kq6HkMZEHR',
  },
  {
    sector: '',
    region: 'Sin especificar',
    display_name: '[PAIS] Bolivia',
    name: '[PAIS] Bolivia',
    country: 'Bolivia',
    id: 'KAsWOXUgaJCG3ghqdS3V',
  },
  {
    name: '[PAIS] Brasil',
    country: 'Brasil',
    region: 'Sin especificar',
    display_name: '[PAIS] Brasil',
    sector: '',
    id: 'No5BYcxD5sPoNqkh8msP',
  },
  {
    country: 'Colombia',
    display_name: '[PAIS] Colombia',
    region: 'Sin especificar',
    name: '[PAIS] Colombia',
    sector: '',
    id: 'CxULGoXmzIB6Wlpm8Fr8',
  },
  {
    display_name: '[PAIS] Cuba',
    country: 'Cuba',
    sector: '',
    region: 'Sin especificar',
    name: '[PAIS] Cuba',
    id: 'b7GlmG9ksNt96om1pOj7',
  },
  {
    country: 'Chile',
    display_name: 'Angol',
    name: 'Angol',
    sector: '',
    region: 'La Araucanía',
    id: 'xBj43DrLNF8EqqbxXgTT',
  },
  {
    sector: '',
    display_name: 'Central Alhueco',
    name: 'Central Alhueco',
    region: 'La Araucanía',
    country: 'Chile',
    id: 'ts4oM83m2oXrzZvjyMWF',
  },
  {
    name: 'Cholchol',
    display_name: 'Cholchol',
    country: 'Chile',
    sector: '',
    region: 'La Araucanía',
    id: 'VzFr2ccOgDIaRQWjojtI',
  },
  {
    sector: '',
    region: 'Biobío',
    country: 'Chile',
    name: 'Concepción',
    display_name: 'Concepción',
    id: 'LOffVz30WfsbU6cOTYMK',
  },
  {
    region: 'Biobío',
    country: 'Chile',
    sector: '',
    name: 'Coronel',
    display_name: 'Coronel',
    id: 'iMGg6fQpomAcE3eC0Ao5',
  },
  {
    sector: '',
    country: 'Chile',
    name: 'Cunco',
    display_name: 'Cunco',
    region: 'La Araucanía',
    id: 'ufPFAdHeeSV1EKqCAlGe',
  },
  {
    region: 'La Araucanía',
    sector: '',
    display_name: 'Curaco',
    name: 'Curaco',
    country: 'Chile',
    id: 'vaRAmzZ5fXlUWbOhZMyJ',
  },
  {
    display_name: 'Gorbea',
    region: 'La Araucanía',
    sector: '',
    country: 'Chile',
    name: 'Gorbea',
    id: 'WET6FitdXYItDQHofe3u',
  },
  {
    display_name: 'Hualpín',
    name: 'Hualpín',
    sector: '',
    country: 'Chile',
    region: 'La Araucanía',
    id: 'xEXkVc6L5ubOxTHrutXN',
  },
  {
    name: 'Iquique',
    display_name: 'Iquique',
    country: 'Chile',
    sector: '',
    region: 'Tarapacá',
    id: 'ZXlUWWMC9IHD11FsNQma',
  },
  {
    region: 'Coquimbo',
    sector: '',
    country: 'Chile',
    name: 'La Serena',
    display_name: 'La Serena',
    id: '1uQ0gDImwoa21cAvzaOP',
  },
  {
    region: 'Los Ríos',
    display_name: 'Lanco',
    sector: '',
    name: 'Lanco',
    country: 'Chile',
    id: 'd2CvFTnoGfiDZq1NllrE',
  },
  {
    region: 'La Araucanía',
    country: 'Chile',
    display_name: 'Lautaro',
    sector: '',
    name: 'Lautaro',
    id: '6ZP5rvDlt8SKmKOUekCc',
  },
  {
    name: 'Lonquimay',
    region: 'La Araucanía',
    country: 'Chile',
    display_name: 'Lonquimay',
    sector: '',
    id: 'uRLg5PnpjR6TDklqL5T2',
  },
  {
    region: 'Biobío',
    name: 'Los Ángeles',
    sector: '',
    country: 'Chile',
    display_name: 'Los Ángeles',
    id: 'xO7J5BMNJrmTwo57XqiU',
  },
  {
    sector: '',
    country: 'Chile',
    region: 'Los Ríos',
    display_name: 'Los Lagos',
    name: 'Los Lagos',
    id: 'lc00O4sCCH2aswRhIF28',
  },
  {
    name: 'Neuquén',
    region: 'Sin especificar',
    sector: '',
    country: 'Argentina',
    display_name: 'Neuquén',
    id: 'je1g9iVVjWvABVWjEJl4',
  },
  {
    region: 'Los Lagos',
    name: 'Osorno',
    display_name: 'Osorno',
    country: 'Chile',
    sector: '',
    id: 'QFphjjXKUB2NLCQrA9r2',
  },
  {
    sector: '',
    name: 'Paillao Mapu',
    country: 'Chile',
    display_name: 'Paillao Mapu',
    region: 'La Araucanía',
    id: 'HAzoSArOdKZ5sowQJLEj',
  },
  {
    country: 'Chile',
    display_name: 'Panguipulli',
    sector: '',
    name: 'Panguipulli',
    region: 'Los Ríos',
    id: '3Suze7mE4syZPpQFrwOd',
  },
  {
    country: 'Chile',
    sector: '',
    name: 'Pitrufquén',
    display_name: 'Pitrufquén',
    region: 'La Araucanía',
    id: 'f8joAY11p4DXIroDjfY0',
  },
  {
    country: 'Chile',
    display_name: 'Pucón',
    sector: '',
    region: 'La Araucanía',
    name: 'Pucón',
    id: 'd1ROl0bDv2QVbCOgbISY',
  },
  {
    display_name: 'Puerto Montt',
    name: 'Puerto Montt',
    country: 'Chile',
    sector: '',
    region: 'Los Lagos',
    id: 'WmYuIfhkbtcgiVOWFLUC',
  },
  {
    sector: '',
    region: 'La Araucanía',
    display_name: 'Pullallán',
    name: 'Pullallán',
    country: 'Chile',
    id: 'Iyltmgffn7SibcwIfFOB',
  },
  {
    country: 'Chile',
    display_name: 'Punta Arenas',
    region: 'Magallanes',
    name: 'Punta Arenas',
    sector: '',
    id: 'tC2yKz98Dawu2O1heWR2',
  },
  {
    name: 'Rancagua',
    sector: '',
    display_name: 'Rancagua',
    country: 'Chile',
    region: "O'Higgins",
    id: 'lcqTJRWm8EXouwoUeYyy',
  },
  {
    sector: '',
    country: 'Chile',
    display_name: 'Rucacura',
    name: 'Rucacura',
    region: 'La Araucanía',
    id: 'j0ikeFUtu0hkatiwm2ps',
  },
  {
    country: 'Argentina',
    name: 'San Martín',
    region: 'Sin especificar',
    display_name: 'San Martín',
    sector: '',
    id: 'WcGGpvtc1Yl344iIl7aW',
  },
  {
    display_name: 'Santiago - Centro',
    name: 'Santiago',
    country: 'Chile',
    region: 'Metropolitana',
    sector: 'Centro',
    id: '3adoInFvVnz8nY1ENpnV',
  },
  {
    sector: 'Cerrillos',
    display_name: 'Santiago - Cerrillos',
    name: 'Santiago',
    country: 'Chile',
    region: 'Metropolitana',
    id: 'SogN0FdqG7SgUy2brUCt',
  },
  {
    country: 'Chile',
    sector: 'Colina',
    name: 'Santiago',
    display_name: 'Santiago - Colina',
    region: 'Metropolitana',
    id: 'HLUqTRJoYybkGhYVEz1J',
  },
  {
    name: 'Santiago',
    display_name: 'Santiago - La Cisterna',
    country: 'Chile',
    region: 'Metropolitana',
    sector: 'La Cisterna',
    id: 'Q7t1P7INYoEFAa6Tr8aM',
  },
  {
    name: 'Santiago',
    sector: 'La Florida',
    region: 'Metropolitana',
    country: 'Chile',
    display_name: 'Santiago - La Florida',
    id: 'C7TacGjbpKnFghCTBHG5',
  },
  {
    sector: 'Las Condes',
    display_name: 'Santiago - Las Condes',
    country: 'Chile',
    region: 'Metropolitana',
    name: 'Santiago',
    id: 'AB0mvm3YcByoLDJ6lWdp',
  },
  {
    sector: 'Maipú',
    region: 'Metropolitana',
    country: 'Chile',
    name: 'Santiago',
    display_name: 'Santiago - Maipú',
    id: 'FgRnZ7Rvtz1QzePYnFQx',
  },
  {
    display_name: 'Santiago - Peñaflor',
    region: 'Metropolitana',
    sector: 'Peñaflor',
    name: 'Santiago',
    country: 'Chile',
    id: 'mbqUtN71SMoFuuj9UMVn',
  },
  {
    country: 'Chile',
    region: 'Metropolitana',
    name: 'Santiago',
    display_name: 'Santiago - Peñalolén',
    sector: 'Peñalolén',
    id: 'wVsebB9Pb2RWtBEi91KU',
  },
  {
    display_name: 'Santiago - Pudahuel',
    region: 'Metropolitana',
    sector: 'Pudahuel',
    country: 'Chile',
    name: 'Santiago',
    id: 'BLVgZ7SH39bD2ODYXNSw',
  },
  {
    name: 'Santiago',
    sector: 'Puente Alto',
    region: 'Metropolitana',
    display_name: 'Santiago - Puente Alto',
    country: 'Chile',
    id: 'hxQnb5qdYtMggK3oxmWd',
  },
  {
    region: 'Metropolitana',
    country: 'Chile',
    display_name: 'Santiago - Recoleta',
    sector: 'Recoleta',
    name: 'Santiago',
    id: 'Fhv67pJPBwClyY20NKfT',
  },
  {
    display_name: 'Santiago - San Bernardo',
    region: 'Metropolitana',
    country: 'Chile',
    sector: 'San Bernardo',
    name: 'Santiago',
    id: '8OZR6O5cuQB0qABytWAR',
  },
  {
    display_name: 'Talca',
    country: 'Chile',
    region: 'Maule',
    name: 'Talca',
    sector: '',
    id: 'FZR4oJCX9XZKNL0Nu0m7',
  },
  {
    name: 'Talcahuano',
    display_name: 'Talcahuano',
    sector: '',
    country: 'Chile',
    region: 'Biobío',
    id: 'g5sy8X93imRSpykn9pmn',
  },
  {
    sector: '',
    country: 'Chile',
    region: 'La Araucanía',
    name: 'Temuco',
    display_name: 'Temuco',
    id: '38RPBQduDY4Mb9Vp6D94',
  },
  {
    region: 'La Araucanía',
    display_name: 'Temuco - Altamira',
    name: 'Temuco',
    sector: 'Altamira',
    country: 'Chile',
    id: 'PZvJTX0mEtvLntb0nWLz',
  },
  {
    country: 'Chile',
    name: 'Temuco',
    display_name: 'Temuco - Amanecer',
    sector: 'Amanecer',
    region: 'La Araucanía',
    id: 'e2bFVITsv4v1oZ1VFs6b',
  },
  {
    sector: 'Fundo El Carmen',
    country: 'Chile',
    display_name: 'Temuco - Fundo El Carmen',
    name: 'Temuco',
    region: 'La Araucanía',
    id: 'M1Bhje7th6H5nVWFeP7A',
  },
  {
    sector: 'La Paz MacIver',
    display_name: 'Temuco - La Paz MacIver',
    country: 'Chile',
    name: 'Temuco',
    region: 'La Araucanía',
    id: 'ohs0O8tTTs02XMz5Psa2',
  },
  {
    display_name: 'Temuco - Labranza',
    name: 'Temuco',
    region: 'La Araucanía',
    country: 'Chile',
    sector: 'Labranza',
    id: 'Ew8WPKMN3xCxwmoB16Mr',
  },
  {
    sector: 'Las Lomas',
    region: 'La Araucanía',
    country: 'Chile',
    display_name: 'Temuco - Las Lomas',
    name: 'Temuco',
    id: 'XmDLCb4CI9sI56TDi1rl',
  },
  {
    display_name: 'Temuco - Los Caciques',
    name: 'Temuco',
    country: 'Chile',
    sector: 'Los Caciques',
    region: 'La Araucanía',
    id: 'mFupw8XzqgiWvKAmizuR',
  },
  {
    country: 'Chile',
    name: 'Temuco',
    region: 'La Araucanía',
    sector: 'Padre Las Casas',
    display_name: 'Temuco - Padre Las Casas',
    id: 'lOMJBFrVwoXc6YbstcNI',
  },
  {
    name: 'Temuco',
    display_name: 'Temuco - Pedro de Valdivia',
    country: 'Chile',
    sector: 'Pedro de Valdivia',
    region: 'La Araucanía',
    id: 'NyitNypMDJ99k1OPeqCX',
  },
  {
    display_name: 'Temuco - Pueblo Nuevo',
    sector: 'Pueblo Nuevo',
    name: 'Temuco',
    country: 'Chile',
    region: 'La Araucanía',
    id: 'DzaW9yNR1NtgbLbjhcb2',
  },
  {
    region: 'La Araucanía',
    name: 'Temuco',
    sector: 'Trañi Trañi',
    country: 'Chile',
    display_name: 'Temuco - Trañi Trañi',
    id: 'DS3tdaiZ4R1a27NOekUP',
  },
  {
    name: 'Temuco',
    region: 'La Araucanía',
    sector: 'Turingia',
    country: 'Chile',
    display_name: 'Temuco - Turingia',
    id: 'r5vvydrNbATL2m9zKVXV',
  },
  {
    region: 'La Araucanía',
    name: 'Temuco',
    country: 'Chile',
    sector: 'Villa Los Ríos',
    display_name: 'Temuco - Villa Los Ríos',
    id: 'f2GXvo12Dp2oCu5jrVaX',
  },
  {
    country: 'Chile',
    sector: '',
    name: 'Toltén',
    display_name: 'Toltén',
    region: 'La Araucanía',
    id: 'EGZd5LcyK4Kum0D7vbhM',
  },
  {
    sector: '',
    display_name: 'Villarrica',
    region: 'La Araucanía',
    country: 'Chile',
    name: 'Villarrica',
    id: 'BB77XrisnV1AepkKwwss',
  },
];

export default locality_data;
